# Generated by Django 5.2.7 on 2025-10-27 15:45

import group.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("group", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="group",
            name="invite_code",
        ),
        migrations.AddField(
            model_name="group",
            name="access_code",
            field=models.CharField(
                default=group.models.Group.generate_access_code,
                max_length=100,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="rules",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
