# Generated by Django 5.2.7 on 2025-12-27 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Badge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("icon", models.ImageField(blank=True, null=True, upload_to="")),
                ("category", models.CharField(max_length=50)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
    ]
