# Generated by Django 5.2.7 on 2025-11-15 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0002_remove_task_category_task_position_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskboard",
            name="name",
            field=models.CharField(default="Main Board", max_length=255),
        ),
    ]
