# Generated by Django 5.2.7 on 2025-12-02 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0004_alter_taskassignment_assigned_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasklist",
            name="position",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
