# Generated by Django 5.2.7 on 2025-12-02 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0005_alter_tasklist_position"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasklist",
            name="position",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
