# Generated by Django 5.2.7 on 2026-02-06 15:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("task", "0006_alter_tasklist_position"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="assigned_to",
        ),
        # Remove old unique_together constraint first
        migrations.AlterUniqueTogether(
            name="taskassignment",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="taskassignment",
            name="assigned_to",
        ),
        migrations.AddField(
            model_name="taskassignment",
            name="content_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task_assignments",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="taskassignment",
            name="object_id",
            field=models.UUIDField(null=True),
        ),
        # Add new unique_together constraint
        migrations.AlterUniqueTogether(
            name="taskassignment",
            unique_together={("task", "content_type", "object_id")},
        ),
        migrations.AddIndex(
            model_name="taskassignment",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="task_taskas_content_3f8550_idx",
            ),
        ),
    ]
