# Generated by Django 5.2.7 on 2025-10-27 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspace", "0002_alter_workspace_access_code_alter_workspace_rules"),
    ]

    operations = [
        migrations.AlterField(
            model_name="spacemember",
            name="custom_permissions",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
