# Generated by Django 5.2.7 on 2026-02-06 15:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspace", "0003_alter_spacemember_custom_permissions"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkspaceType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("schema", models.JSONField(blank=True, default=dict, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="workspace",
            name="metadata",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name="workspace",
            name="workspace_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="workspaces",
                to="workspace.workspacetype",
            ),
        ),
    ]
