# Generated by Django 5.2.7 on 2026-02-10 16:39

import apps.authentication.models
import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OTP",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "token",
                    models.PositiveBigIntegerField(
                        default=apps.authentication.models.OTP.generate_token,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2026, 2, 10, 16, 54, 7, 259055, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
            ],
        ),
    ]
