# Generated by Django 5.2.7 on 2026-02-10 16:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otp",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 2, 10, 17, 1, 25, 796082, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AddIndex(
            model_name="otp",
            index=models.Index(
                fields=["expires_at"], name="authenticat_expires_98a691_idx"
            ),
        ),
    ]
