# Generated by Django 5.2.7 on 2026-02-10 16:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_alter_otp_expires_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otp",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 2, 10, 17, 1, 40, 455120, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
