# Generated by Django 5.2.7 on 2026-02-10 16:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_alter_otp_expires_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otp",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="otp",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 2, 10, 17, 4, 40, 818273, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
