# Generated by Django 5.2.7 on 2026-02-10 16:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0004_alter_otp_email_alter_otp_expires_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otp",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="otp",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 2, 10, 17, 9, 9, 973059, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
