# Generated by Django 5.2.7 on 2026-02-12 20:45

import apps.authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0005_alter_otp_email_alter_otp_expires_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otp",
            name="expires_at",
            field=models.DateTimeField(
                default=apps.authentication.models.get_otp_expiry
            ),
        ),
    ]
