# Generated by Django 5.2.7 on 2025-10-29 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("group", "0002_remove_group_invite_code_group_access_code_and_more"),
        ("workspace", "0003_alter_spacemember_custom_permissions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="groups",
                to="workspace.workspace",
            ),
        ),
    ]
