# Generated by Django 5.2.7 on 2026-02-04 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("group", "0003_alter_group_workspace"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="group",
            name="channel_count",
        ),
    ]
