# Generated by Django 5.2.7 on 2025-10-25 09:47

import workspace.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspace", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workspace",
            name="access_code",
            field=models.CharField(
                default=workspace.models.Workspace.generate_access_code,
                max_length=100,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="workspace",
            name="rules",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
