# Generated by Django 5.2.7 on 2025-11-16 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="notification_settings",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
