# Generated by Django 5.2.7 on 2026-02-13 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_remove_user_bio_remove_user_completed_tasks_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="profile_picture",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
