# Generated by Django 5.2.7 on 2026-02-15 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_alter_userprofile_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_email_verified",
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
